# Generated by Django 5.1.4 on 2024-12-19 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Пікір')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Қолданушы пікірі',
                'verbose_name_plural': 'Қолданушылар пікірлері',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Пікір')),
                ('file', models.FileField(blank=True, null=True, upload_to='main/subject/homeworks/', verbose_name='Тапсырма құжаты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Үй жұмысы',
                'verbose_name_plural': 'Үй жұмыстары',
            },
        ),
        migrations.CreateModel(
            name='UserHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(upload_to='main/subject/user/homeworks/', verbose_name='Тапсырма')),
                ('grade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Пікір')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='progress.homework', verbose_name='Үй жұмысы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Білім алушы')),
            ],
            options={
                'verbose_name': 'Қолданушының үй жұмысы',
                'verbose_name_plural': 'Қолданушылардың үй жұмыстары',
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы ұпай пайызы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='main.subject', verbose_name='Пән')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының пәні',
                'verbose_name_plural': 'Қолданушының пәндері',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Сабақтың баллы')),
                ('completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='main.lesson', verbose_name='Сабақ')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='progress.usersubject', verbose_name='Қолданушының пәні')),
            ],
            options={
                'verbose_name': 'Қолданушының сабағы',
                'verbose_name_plural': 'Қолданушылардың сабақтары',
                'unique_together': {('user_subject', 'lesson')},
            },
        ),
    ]
