# Generated by Django 5.1.4 on 2024-12-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='total_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы ұпай пайызы'),
        ),
    ]
