# Generated by Django 5.1.4 on 2024-12-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lesson_subject'),
        ('progress', '0002_usersubject_total_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Сабақтың баллы')),
                ('completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='main.lesson', verbose_name='Сабақ')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='progress.usersubject', verbose_name='Қолданушының пәні')),
            ],
            options={
                'verbose_name': 'Қолданушының сабағы',
                'verbose_name_plural': 'Қолданушылардың сабағы',
                'unique_together': {('user_subject', 'lesson')},
            },
        ),
    ]
