# Generated by Django 5.1.4 on 2024-12-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='books/posters/', verbose_name='Постер'),
        ),
    ]
