# Generated by Django 5.1.4 on 2024-12-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_file_book_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
