# Generated by Django 5.1.4 on 2024-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=100, verbose_name='Тегі')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторлар',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.author', verbose_name='Авторлар'),
        ),
    ]
