# Generated by Django 5.1.4 on 2024-12-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Қаралым'),
        ),
    ]
