# Generated by Django 5.1.4 on 2024-12-19 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Атауы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Кілттік атауы')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('lesson_type', models.CharField(choices=[('theory', 'Теориялық сабақ'), ('practice', 'Практикалық сабақ'), ('sync', 'Синхронды сабақ'), ('async', 'Асинхронды сабақ')], max_length=255, verbose_name='Сабақтың түрі')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Видео уақыт')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.chapter', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
            },
        ),
        migrations.CreateModel(
            name='FrameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL сілтеме')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_contents', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Фрейм контент',
                'verbose_name_plural': 'Фрейм контенттер',
            },
        ),
        migrations.CreateModel(
            name='LessonDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('file', models.FileField(blank=True, null=True, upload_to='main/lesson/docs/', verbose_name='Файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Сабақ құжаты',
                'verbose_name_plural': 'Сабақ құжаттары',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='main/subject/posters', verbose_name='Постер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Қаралым')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.category', verbose_name='Категория')),
                ('observers', models.ManyToManyField(blank=True, related_name='access_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Жазылушылар')),
            ],
            options={
                'verbose_name': 'Пән',
                'verbose_name_plural': 'Пәндер',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.subject', verbose_name='Пәндер'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.subject', verbose_name='Пәндер'),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Мәтін')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Мәтін контент',
                'verbose_name_plural': 'Мәтін контенттер',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сілтеме')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Видео уақыт')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contents', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Видео контент',
                'verbose_name_plural': 'Видео контенттер',
            },
        ),
    ]
