# Generated by Django 5.1.4 on 2024-12-14 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='main/subject/posters', verbose_name='Постер'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(upload_to='main/subject/homeworks/', verbose_name='Тапсырма')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Пікір')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=True, verbose_name='Орындалды')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='main.lesson', verbose_name='Сабақ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Білім алушы')),
            ],
        ),
    ]
