# Generated by Django 5.1.4 on 2024-12-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сабақтың уақыты (мин)'),
        ),
    ]
