# Generated by Django 5.1.4 on 2024-12-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ұзақтығы (апта)'),
        ),
    ]
