# Generated by Django 5.1.4 on 2024-12-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='main/courses/posters', verbose_name='Постер'),
        ),
    ]
