# Generated by Django 5.1.4 on 2024-12-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.TextField(verbose_name='Тақырыбы'),
        ),
    ]
