# Generated by Django 5.1.4 on 2024-12-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_module_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тақырыбы')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Мәтіні')),
                ('question_order', models.PositiveSmallIntegerField(default=0, verbose_name='Сұрақ нөмері')),
            ],
            options={
                'verbose_name': 'Олимпиада есебі',
                'verbose_name_plural': 'Олимпиада есептері',
            },
        ),
    ]
