# Generated by Django 5.1.4 on 2024-12-24 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_olympic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOlympic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Пікірі')),
                ('file', models.FileField(upload_to='main/olympics/files/', verbose_name='Файл')),
                ('status', models.BooleanField(default=False, verbose_name='Статаус')),
                ('olympic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_olympics', to='main.olympic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Олимпиада есебі',
                'verbose_name_plural': 'Олимпиада есептері',
            },
        ),
    ]
