# Generated by Django 5.1.4 on 2024-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Видео уақыт'),
        ),
    ]
