# Generated by Django 5.1.4 on 2024-12-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='duration',
        ),
    ]
