# Generated by Django 5.1.4 on 2024-12-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_videocontent_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пән', 'verbose_name_plural': 'Пәндер'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Теориялық сабақ'), ('practice', 'Практикалық сабақ'), ('sync', 'Синхронды сабақ'), ('async', 'Асинхронды сабақ')], max_length=255, verbose_name='Сабақтың түрі'),
        ),
    ]
