# Generated by Django 5.1.4 on 2024-12-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_subject_options_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('file', models.FileField(blank=True, null=True, upload_to='main/lesson/docs/', verbose_name='Файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='main.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Сабақ құжаты',
                'verbose_name_plural': 'Сабақ құжаттары',
            },
        ),
    ]
